import { Button, Container, Grid, Typography } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import ROUTES from "../src/config/routes";
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Container>
        <Grid container mt={2}>
          <Grid item xs={6} mb={4}>
            <Typography
              variant="h4"
            >
              Home Controll Expenses
            </Typography>
          </Grid>
          <Grid container mb={2}>
            <Link
              href={{
                pathname: ROUTES.expenses.list
              }}
            >
              <Button
                variant="outlined"

              >
                Expenses
              </Button>
            </Link>

            <Link
              href={{
                pathname: ROUTES.categories.list
              }}
            >
              <Button
                variant="outlined"

              >
                Categories
              </Button>
            </Link>

          </Grid>
        </Grid>
      </Container>
    </div>
  )
}

export default Home
